a={"apple", "banana", "cherry"}
print(a)
thisset = set(("apple", "banana", "cherry"))
print(thisset)
a.add(3)
print(a)
a.remove("banana")
print(a)
a.update(["orange", "mango", "grape"])
print(a)
a.discard("apple")
print(a)
print(union := a.union({"kiwi", "melon"}))
print(a.intersection({"kiwi", "melon", "grape"}))
print(a.difference({"kiwi","melon"}))
print(a.discard("mango"))